[module]
name = "files"
description = "Common files shared across machines"

[links]
"profile-picture.jpg" = "~/Pictures/profile-picture.jpg"
"zoom-background.jpg" = "~/Pictures/zoom-background.jpg"

[setup]
post_link = ["mkdir -p ~/Code"]
