[module]
name = "zsh"
description = "Zsh shell configuration"

[links]
".zshrc" = "~/.zshrc"
"conf.d" = "~/.config/zsh"

[setup]
post_link = [{ name = "create-local-zsh", run = "touch ~/local.zsh" }]

[deps]
brew = ["zsh"]
