[module]
name = "macos"
description = "macOS system preferences"

[links]
"wallpaper.jpg" = "~/Documents/Images/wallpaper.jpg"

[deps]
brew = ["desktoppr"]

[setup]
post_link = [
  "osascript -e 'tell application \"System Events\" to tell appearance preferences to set dark mode to true'",
  "defaults write com.apple.dock autohide -bool true",
  "defaults write com.apple.dock magnification -bool false",
  "defaults write com.apple.dock persistent-apps -array",
  "defaults write com.apple.dock persistent-others -array",
  "defaults write com.apple.dock recent-apps -array",
  "defaults write com.apple.dock show-recents -bool false",
  "defaults write com.apple.dock wvous-tl-corner -int 0",
  "defaults write com.apple.dock wvous-tr-corner -int 0",
  "defaults write com.apple.dock wvous-bl-corner -int 0",
  "defaults write com.apple.dock wvous-br-corner -int 4",
  "defaults write com.apple.menuextra.clock ShowSeconds -bool true",
  "defaults write com.apple.WindowManager StandardHideWidgets -bool true",
  "defaults write com.apple.WindowManager StageManagerHideWidgets -bool true",
  "defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false",
  "defaults write NSGlobalDomain com.apple.keyboard.fnState -bool true",
  "defaults write com.google.Chrome NSUserKeyEquivalents -dict-add 'New Tab to the Right' '@~t'",
  "desktoppr ~/Documents/Images/wallpaper.jpg",
  "sudo dscl . delete /Users/$USER JPEGPhoto 2>/dev/null || true",
  "sudo dscl . create /Users/$USER Picture ~/Documents/Images/profile-picture.jpg",
  "killall Dock",
  "killall SystemUIServer",
]
