[module]
name = "macos"
description = "macOS system preferences"

[links]
"wallpaper.jpg" = "~/Documents/Images/wallpaper.jpg"
"shrink-density.sh" = "~/.config/macos/shrink-density.sh"

[deps]
brew = ["desktoppr", "displayplacer"]

[setup]
post_link = [
  "defaults write NSGlobalDomain AppleInterfaceStyle -string Dark",
  "defaults write com.apple.dock autohide -bool true",
  "defaults write com.apple.dock magnification -bool false",
  "defaults write com.apple.dock wvous-tl-corner -int 0",
  "defaults write com.apple.dock wvous-tr-corner -int 0",
  "defaults write com.apple.dock wvous-bl-corner -int 0",
  "defaults write com.apple.dock wvous-br-corner -int 4",
  "defaults write com.apple.menuextra.clock ShowSeconds -bool true",
  "desktoppr ~/Documents/Images/wallpaper.jpg",
  "bash ~/.config/macos/shrink-density.sh",
  "killall Dock",
  "killall SystemUIServer",
]
